.\" Written by Kurt Lust, kurt.lust@uantwerpen.be.
.TH man 1 "19 February 2018" "1.0" "torque-hosts-parallel command"
.SH NAME
torque-hosts-parallel \- Experimental tool to generate a hostlist for
GNU parallel (-S argument) for a Torque job.
.SH SYNOPSIS
torque-hosts-parallel
.SH DESCRIPTION
torque-hosts-parallel is an experimental tool to generate a hostlist 
(as a single string) that can be used for the -S argument of GNU parallel.
It is part of the torque-tools package.
.SH OPTIONS
The current experimental implementation does not support command line options.
.SH EXAMPLE
In a Torque job or interactive job, after loading the appropriate modules
(parallel for GNU parallel and the torque-tools module), try:

.Li 107
seq 1 $(torque-host-per-line | wc -l) | parallel -S $(torque-hosts-parallel) -q bash -c 'echo "$HOSTNAME"'

Or to see what the line looks like, simply execute:

.Li 22
torque-hosts-parallel

or

.Li 30
echo $(torque-hosts-parallel)

.SH COMMENTS
We're interested in ways people would use this so that we can further extend
the command as needed. Pleace contact hpc@uantwerpen.be.
.SH SEE ALSO
torque-tools(1), torque-tasks(1), torque-lprocs(1), torque-hoststring(1),
torque-host-per-line(1)
.SH BUGS
No known bugs.
.SH AUTHOR
Kurt Lust (Kurt.Lust@uantwerpen.be)